# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
    Congratulations on having your first pull request merged!
    Looking forward to seeing your future work :smile: :tada: :fireworks:
